# Generated by Django 3.2.7 on 2021-09-25 15:35

import Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210925_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isThermostat', models.BooleanField(default=False)),
                ('isLight', models.BooleanField(default=False)),
                ('is_on', models.BooleanField(default=False)),
                ('tempature', models.CharField(max_length=200, validators=[Api.models.validate_temp])),
            ],
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.TimeField(auto_now_add=True)),
                ('isThermostat', models.BooleanField(default=False)),
                ('isLight', models.BooleanField(default=False)),
                ('is_on', models.BooleanField(default=False)),
                ('tempature', models.CharField(max_length=200, validators=[Api.models.validate_temp])),
            ],
        ),
        migrations.DeleteModel(
            name='Light',
        ),
        migrations.DeleteModel(
            name='Thermostat',
        ),
    ]
