# Generated by Django 3.2.7 on 2021-09-25 16:19

import Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210925_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaction',
            name='time',
        ),
        migrations.RemoveField(
            model_name='logaction',
            name='title',
        ),
        migrations.AddField(
            model_name='logaction',
            name='device_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logaction',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='update_time'),
        ),
        migrations.AlterField(
            model_name='logaction',
            name='tempature',
            field=models.CharField(max_length=3, validators=[Api.models.validate_temp]),
        ),
    ]
