# Generated by Django 3.2.7 on 2021-09-25 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210925_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaction',
            name='device_id',
        ),
        migrations.AddField(
            model_name='logaction',
            name='title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logaction',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
