# Generated by Django 3.2.7 on 2021-09-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_rename_is_on_logaction_ison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logaction',
            old_name='title',
            new_name='device_id',
        ),
    ]
