# Generated by Django 3.2.7 on 2021-09-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_rename_title_logaction_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaction',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.device'),
        ),
    ]
